version: '4'
services:
  backend:
    build: .
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/DoAn
      - REDIRECT_URI=http://127.0.0.1:8002/ext/auth/code
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: